package main

import (
	"bufio"
	"fmt"
	"io"
	"path"
	"strings"
)

// ExtractFromScript scans a shell script for "ln -s" invocations and
// turns each one into an Entry. Only a restricted grammar is
// understood: one ln call per line, flags limited to -s/-f in any
// combination, and exactly two plain or quoted path operands. No
// variable expansion, globbing, or line continuation is attempted.
//
// In strict mode any line that starts with "ln" but doesn't fit that
// grammar aborts extraction, because silently dropping a symlink
// while migrating a dotfiles repo is worse than stopping. In lenient
// mode such lines are reported on warn and skipped instead.
func ExtractFromScript(r io.Reader, lenient bool, warn io.Writer) ([]Entry, error) {
	var entries []Entry
	scanner := bufio.NewScanner(r)
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		words, err := splitShellWords(line)
		if err != nil {
			if !lenient {
				return nil, fmt.Errorf("line %d: %v", lineNo, err)
			}
			fmt.Fprintf(warn, "skipping line %d: %v\n", lineNo, err)
			continue
		}
		if len(words) == 0 || words[0] != "ln" {
			continue
		}
		source, target, err := parseLnArgs(words[1:], lenient)
		if err != nil {
			if !lenient {
				return nil, fmt.Errorf("line %d: %v", lineNo, err)
			}
			fmt.Fprintf(warn, "skipping line %d: %v\n", lineNo, err)
			continue
		}
		if source == "" {
			continue // recognized as ln, but not a symlink call (e.g. a hard link)
		}
		entries = append(entries, Entry{Target: target, Source: source, Line: lineNo})
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return entries, nil
}

// parseLnArgs interprets the arguments to ln after the command name.
// It returns an empty source (with no error) when the line is a valid
// ln call that just isn't a symlink, so the caller can skip it.
func parseLnArgs(args []string, lenient bool) (source, target string, err error) {
	var operands []string
	sawSymlinkFlag := false
	for _, a := range args {
		if a != "-" && strings.HasPrefix(a, "-") {
			for _, f := range a[1:] {
				switch f {
				case 's':
					sawSymlinkFlag = true
				case 'f':
					// force: irrelevant, GenerateScript always overwrites
				default:
					if !lenient {
						return "", "", fmt.Errorf("unsupported ln flag -%c (use --lenient to ignore it)", f)
					}
				}
			}
			continue
		}
		operands = append(operands, a)
	}
	if !sawSymlinkFlag {
		return "", "", nil
	}
	if len(operands) != 2 {
		return "", "", fmt.Errorf("expected exactly 2 paths after ln, got %d", len(operands))
	}
	return operands[0], operands[1], nil
}

// splitShellWords does minimal word-splitting: it understands single
// and double quotes and backslash escapes inside double quotes, but
// nothing else about shell syntax. Variable expansion is rejected
// outright since we can't evaluate it.
func splitShellWords(s string) ([]string, error) {
	var words []string
	var cur strings.Builder
	inWord := false
	i := 0
	for i < len(s) {
		c := s[i]
		switch {
		case c == '\'':
			j := strings.IndexByte(s[i+1:], '\'')
			if j < 0 {
				return nil, fmt.Errorf("unterminated single quote")
			}
			cur.WriteString(s[i+1 : i+1+j])
			i += j + 2
			inWord = true
		case c == '"':
			end := -1
			for k := i + 1; k < len(s); k++ {
				if s[k] == '\\' && k+1 < len(s) {
					k++
					continue
				}
				if s[k] == '"' {
					end = k
					break
				}
			}
			if end < 0 {
				return nil, fmt.Errorf("unterminated double quote")
			}
			inner := strings.NewReplacer(`\"`, `"`, `\\`, `\`).Replace(s[i+1 : end])
			cur.WriteString(inner)
			i = end + 1
			inWord = true
		case c == ' ' || c == '\t':
			if inWord {
				words = append(words, cur.String())
				cur.Reset()
				inWord = false
			}
			i++
		case c == '$':
			return nil, fmt.Errorf("variable expansion is not supported")
		case c == '#':
			i = len(s)
		default:
			cur.WriteByte(c)
			inWord = true
			i++
		}
	}
	if inWord {
		words = append(words, cur.String())
	}
	return words, nil
}

// GenerateScript writes a POSIX shell script that recreates the given
// entries as symlinks. $HOME is left as a shell variable, and the
// dotfiles repo is located relative to the script itself, so the
// script keeps working regardless of where the repo is checked out.
func GenerateScript(w io.Writer, entries []Entry) error {
	fmt.Fprintln(w, "#!/bin/sh")
	fmt.Fprintln(w, "# generated by dotconv to-script - do not edit by hand")
	fmt.Fprintln(w, `REPO="$(cd "$(dirname "$0")" && pwd)"`)
	fmt.Fprintln(w)
	for _, e := range entries {
		target := targetExpr(e.Target)
		fmt.Fprintf(w, "mkdir -p %q\n", path.Dir(target))
		fmt.Fprintf(w, "ln -sf \"$REPO/%s\" %q\n", e.Source, target)
	}
	return nil
}

func targetExpr(target string) string {
	if strings.HasPrefix(target, "~/") {
		return "$HOME/" + target[2:]
	}
	return target
}
